Remake
csunibo/Diariotirocinio pull request #3
Opened 2024-07-08 12:15 UTC by samuelemusiani

Mentre mi esercitavo per Tecweb ho deciso di rifare questo sito che mi sembrava un po' antiquato. L'ho fatto in Vue perché è il framework che ho imparato. È vero che Dynamik è in svelte però secondo me ci sta differenziare un po' i framework così possiamo attirare più gente per contribuire.

Ritengo di essere già arrivato ad un buon punto per una PR. Ci sarebbero altre cose da fare per migliorare il codice ma le farei piano piano nel tempo senza appesantire ancora di più questa PR

Se viene approvata poi lo metterei anche hostato in adm magari sotto `diario.students.cs.unibo.it`

2024-07-08 13:08 UTC, foxyseta commented
Ho messo come recensore il man @kocierik perché ci ha lavorato lui e io non ho mai fatto un tirocinio.

2024-07-08 13:27 UTC, kocierik commented
Ci guardo in giornata 👍

2024-07-08 13:37 UTC, samuelemusiani commented
Mi sono scordato di mettere il deploy per pages nuovo, ~~dopo~~ **domani** lo faccio

2024-07-09 09:26 UTC, kocierik requested changes

2024-07-09 09:26 UTC, kocierik commented on src/components/InfoMenu.vue
> +        class="bg-csunibo-light-blu w-80 h-full shadow-2xl border-black flex flex-col justify-between"
aggiungerei un overflow-scroll, dal mio pc non riesco a vedere l'ultimo bottone (contribuisci)

2024-07-09 09:27 UTC, kocierik commented
A livello di funzionalita' direi che va piu' che bene, ho notato che da mobile c'e' uno scroll orizzontale dovuto a un qualche padding penso

2024-07-09 12:27 UTC, samuelemusiani commented
Ho aggiustato l'overflow sul menu e ho risolto un piccolo problema che si aveva con i pulsanti del menu in schermi piccoli. Non ho trovato lo scroll orizzontale che dici, puoi dirmi nello specifico come lo hai ottenuto?

Dopo aggiungo il deploy per pages e direi che ci siamo

2024-07-09 18:22 UTC, samuelemusiani commented
@kocierik dire che ci siamo anche con il deploy

2024-07-10 08:26 UTC, kocierik approved these changes

2024-07-10 08:28 UTC, kocierik commented
> Ho aggiustato l'overflow sul menu e ho risolto un piccolo problema che si aveva con i pulsanti del menu in schermi piccoli. Non ho trovato lo scroll orizzontale che dici, puoi dirmi nello specifico come lo hai ottenuto?
> 
> Dopo aggiungo il deploy per pages e direi che ci siamo

avevo provato dal mio telefono muovendomi da sinistra verso destra, se non c'e' da te magari avevo zoomato io per errore

2024-07-10 09:06 UTC, samuelemusiani commented
> avevo provato dal mio telefono muovendomi da sinistra verso destra, se non c'e' da te magari avevo zoomato io per errore

Mergio e provo anche su altri telefoni, se lo noto risolvo

2024-07-10 09:06 UTC, merged